#!/bin/sh
# $OpenBSD: Xsetup_0,v 1.6 2019/06/29 13:33:06 espie Exp $

OS_NAME=$(uname -sr)

xrandr --output default --dpi 96
xsetroot -solid $(xrdb -query | awk '/xroot.background/ { print $2 }')
xclock -digital -strftime "$OS_NAME | %A %d %B %y %H:%M:%S " &

xsetroot -solid black

#  install package openbsd-backgrounds
#  then uncomment:
#
# if test -x /usr/local/bin/openbsd-wallpaper
# then
# 	/usr/local/bin/openbsd-wallpaper
# fi

# sxpm OpenBSD.xpm &
