xrandr --setprovideroutputsource modesetting NVIDIA-0 
xrandr -s 2048x1152 -r 60 
#xrandr -s 2048x1152 -r 60 & 
xrdb -merge ~/.Xresources &
#xscreensaver -no-splash &
sleep 5; feh --bg-scale ~/.config/home_scripts/wallpaper.jpg &
sleep 5; telegram-desktop &
sleep 5; tint2 &
cwm
